In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imbalanced-data-practice/sample_submission.csv
/kaggle/input/imbalanced-data-practice/aug_test.csv
/kaggle/input/imbalanced-data-practice/aug_train.csv

In [3]:
df = pd.read_csv('/kaggle/input/imbalanced-data-practice/aug_train.csv', encoding='latin1')

In [4]:
df.shape

(382154, 12)

In [5]:
df.head(10)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
5,295775,Female,25,1,25.0,1,< 1 Year,No,27954.0,152.0,23,0
6,71711,Male,51,1,8.0,0,1-2 Year,Yes,2630.0,26.0,209,0
7,331781,Male,38,1,28.0,1,1-2 Year,No,2630.0,26.0,51,0
8,290704,Female,45,1,28.0,0,1-2 Year,Yes,55873.0,124.0,262,0
9,344792,Male,42,1,28.0,0,1-2 Year,Yes,27801.0,122.0,217,1

In [6]:
column_to_keep = ['Gender','Vehicle_Damage']
df = df[column_to_keep]

In [7]:
df.isnull().sum()

Gender            0
Vehicle_Damage    0
dtype: int64

In [8]:
df.Vehicle_Damage.value_counts()

Vehicle_Damage
No     198501
Yes    183653
Name: count, dtype: int64

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

print("Columns in dataset:", df.columns)

if 'Gender' not in df.columns or 'Vehicle_Damage' not in df.columns:
    raise KeyError("Expected columns 'Gender' and 'Vehicle_Damage' not found in the dataset.")

df['Vehicle_Damage'] = df['Vehicle_Damage'].map({'No': 0, 'Yes': 1})

classifiers = {
    'Multinomial Naive Bayes': MultinomialNB(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC(),
    'Logistic Regression': LogisticRegression()
}

for name, clf in classifiers.items():

    corpus = df['Gender'].astype(str).tolist()
    target = df['Vehicle_Damage']
    
    
    vectorizer = CountVectorizer()
    transformer = TfidfTransformer()
    classifier = clf
    model = Pipeline([
        ('vectorizer', vectorizer),
        ('transformer', transformer),
        ('classifier', classifier)
    ])

 
    X_train, X_test, y_train, y_test = train_test_split(corpus, target, test_size=0.3, random_state=42)

  
    model.fit(X_train, y_train)

   
    predictions = model.predict(X_test)

    
    accuracy = accuracy_score(y_test, predictions)
    report = classification_report(y_test, predictions)

   
    print(f'\nResults for {name}:')
    print(f'Accuracy: {accuracy}')
    print(f'Classification Report:\n{report}')

Columns in dataset: Index(['Gender', 'Vehicle_Damage'], dtype='object')

Results for Multinomial Naive Bayes:
Accuracy: 0.5474892496096714
Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.51      0.54     59408
           1       0.53      0.59      0.55     55239

    accuracy                           0.55    114647
   macro avg       0.55      0.55      0.55    114647
weighted avg       0.55      0.55      0.55    114647


Results for Decision Tree:
Accuracy: 0.5474892496096714
Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.51      0.54     59408
           1       0.53      0.59      0.55     55239

    accuracy                           0.55    114647
   macro avg       0.55      0.55      0.55    114647
weighted avg       0.55      0.55      0.55    114647


Results for Random Forest:
Accuracy: 0.5474892496096714
Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.51      0.54     59408
           1       0.53      0.59      0.55     55239

    accuracy                           0.55    114647
   macro avg       0.55      0.55      0.55    114647
weighted avg       0.55      0.55      0.55    114647